# ONE
http.get./schema/monitoringconfig/{id}:
  summary: Fetch MonitoringConfig
  description: Fetch MonitoringConfig from database
  fn: com.biz.schema.monitoringconfig.one
  params:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    '200':
      content:
        application/json:
          schema:
            type: object

# CREATE
http.post./schema/monitoringconfig:
  summary: Create a new MonitoringConfig
  description: Create MonitoringConfig from database
  fn: com.biz.schema.monitoringconfig.create
  body:
    content:
      application/json:
        schema:
          $ref: '#/definitions/schema/MonitoringConfig'
  responses:
    '201':
      content:
        application/json:
          schema:
            type: object

# UPDATE
http.put./schema/monitoringconfig/{id}:
  summary: Update a MonitoringConfig
  description: Update MonitoringConfig from database
  fn: com.biz.schema.monitoringconfig.update
  body:
    content:
      application/json:
        schema:
          $ref: '#/definitions/schema/MonitoringConfig'
  params:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    '204':
      content:
        application/json:
          schema:
            type: object

# DELETE
http.delete./schema/monitoringconfig/{id}:
  summary: Delete a MonitoringConfig
  description: Delete MonitoringConfig from database
  fn: com.biz.schema.monitoringconfig.delete
  params:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    '202':
      content:
        application/json:
          schema:
            type: object

# SEARCH
http.post./schema/monitoringconfig/search:
  summary: Fetch multiple MonitoringConfig
  description: Fetch multiple MonitoringConfig from database
  fn: com.biz.schema.monitoringconfig.search
  body:
    content:
      application/json:
        schema:
          type: object
  responses:
    '200':
      content:
        application/json:
          schema:
            type: array

