# ONE
http.get./schema/project/{id}:
  summary: Fetch Project
  description: Fetch Project from database
  fn: com.biz.schema.project.one
  params:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    '200':
      content:
        application/json:
          schema:
            type: object

# CREATE
http.post./schema/project:
  summary: Create a new Project
  description: Create Project from database
  fn: com.biz.schema.project.create
  body:
    content:
      application/json:
        schema:
          $ref: '#/definitions/schema/Project'
  responses:
    '201':
      content:
        application/json:
          schema:
            type: object

# UPDATE
http.put./schema/project/{id}:
  summary: Update a Project
  description: Update Project from database
  fn: com.biz.schema.project.update
  body:
    content:
      application/json:
        schema:
          $ref: '#/definitions/schema/Project'
  params:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    '204':
      content:
        application/json:
          schema:
            type: object

# DELETE
http.delete./schema/project/{id}:
  summary: Delete a Project
  description: Delete Project from database
  fn: com.biz.schema.project.delete
  params:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    '202':
      content:
        application/json:
          schema:
            type: object

# SEARCH
http.post./schema/project/search:
  summary: Fetch multiple Project
  description: Fetch multiple Project from database
  fn: com.biz.schema.project.search
  body:
    content:
      application/json:
        schema:
          type: object
  responses:
    '200':
      content:
        application/json:
          schema:
            type: array

