Project:
  type: object
  properties:
    name:
      type: string
    description:
      type: string
      nullable: true
    ownerId:
      type: string
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
Service:
  type: object
  properties:
    name:
      type: string
    projectId:
      type: string
    gitRepoUrl:
      type: string
    typeId:
      type: string
    subtypeId:
      type: string
      nullable: true
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
ServiceType:
  type: object
  properties:
    name:
      type: string
ServiceSubtype:
  type: object
  properties:
    name:
      type: string
    serviceTypeId:
      type: string
Provider:
  type: object
  properties:
    name:
      type: string
    typeId:
      type: string
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
ProviderType:
  type: object
  properties: {}
PricingPlan:
  type: object
  properties:
    providerId:
      type: string
    cost:
      type: number
    billingUnit:
      type: string
      enum:
        - HOUR
        - DAY
        - MONTH
    customConfig:
      type: object
      nullable: true
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
Environment:
  type: object
  properties:
    name:
      type: string
    description:
      type: string
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
Deployment:
  type: object
  properties:
    name:
      type: string
    description:
      type: string
    environmentId:
      type: string
    serviceId:
      type: string
    planId:
      type: string
    status:
      type: string
      enum:
        - PENDING
        - RUNNING
        - SUCCESS
        - FAILED
        - ROLLBACK
    monitoringConfigId:
      type: string
      nullable: true
    telemetryDashboards:
      type: object
      nullable: true
    appVersion:
      type: string
    microServiceVersions:
      type: array
      items:
        type: string
    dbVersion:
      type: string
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
Plan:
  type: object
  properties:
    name:
      type: string
    providerId:
      type: string
    pricingPlanId:
      type: string
      nullable: true
    deploymentConfig:
      type: object
      nullable: true
    monitoringConfigId:
      type: string
      nullable: true
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
MonitoringConfig:
  type: object
  properties:
    logs:
      type: object
      nullable: true
    traces:
      type: object
      nullable: true
    metrics:
      type: object
      nullable: true
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
